### ISSUE TITLE
[Bug] 3.0.0-alpha.19 broke Thermostat

### ISSUE THREAD

**Issue by KipK** [t0bst4r/home-assistant-matter-hub#73]
Climate thermostats commands are broken since 3.0.0-alpa.19

Here are the catched errors when trying to poweron or change a temperature from Google Home:

```
[ 2024-11-07T10:32:14.561Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.thermostat.state: Referencing 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.homeAssistant.state: This value is no longer available because its context has exited (1)
  at get value [as value] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:122:15)
  at descriptor.get [as entity] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:150:49)
  at _HeatingThermostatServer.targetTemperatureChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2208:42)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
  at emitChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:332:30)
  at Object.postCommit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:338:12)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:465:39
  at MaybePromise.then (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Promises.js:100:17)
  at postCommitNextParticipant (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:464:27)
```

**Comment by t0bst4r** [comment]
I have just released the refactoring. Could you please test?

**Comment by pkoutsovasilis** [comment]
> I have just released the refactoring. Could you please test?

with the latest release I am getting this error at starting

```
matterhub-1  | Behaviors have errors
matterhub-1  |       at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
matterhub-1  |       at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
matterhub-1  |       at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
matterhub-1  |       Cause #0: Error initializing 7515dde831d545e28af9bb707b38216e.aggregator.climate_takis_mqtt_hvac.thermostat
matterhub-1  |         at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
matterhub-1  |       Caused by: Validating 7515dde831d545e28af9bb707b38216e.aggregator.climate_takis_mqtt_hvac.thermostat.state.minSetpointDeadBand: Conformance "AUTO": Matter requires you to set this attribute (128)
matterhub-1  |         at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
matterhub-1  |         at Object.minSetpointDeadBand (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15)
matterhub-1  |         at validateStruct (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/ValueValidator.js:189:23)
matterhub-1  |         at Object.validate (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:41:7)
matterhub-1  |         at finalizeState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/ServerBehaviorBacking.js:22:23)
```

**Comment by t0bst4r** [comment]
i'll have a look

**Comment by t0bst4r** [comment]
Maybe someone can explain climate devices to me again 😀 

Having those attributes from Home Assistant:

```yaml
hvac_modes:
  - "off"
  - heat
  - cool
  - heat_cool
  - dry
  - fan_only
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes:
  - quiet
  - low
  - medium
  - high
  - turbo
  - auto
current_temperature: 20.1
temperature: 24
min_temp: 10
max_temp: 40
fan_mode: high
last_on_operation: fan_only
device_code: 1400
manufacturer: Samsung
supported_models:
  - Unknown
supported_controller: Broadlink
commands_encoding: Base64
icon: hass:air-conditioner
friendly_name: Family Room AC
supported_features: 393
```

In matter i have the following required properties:

- For all climates
  - localTemperature (numeric)
  - systemMode (off, auto, cool, heat, emergency heat, precooling, fanonly, dry, sleep)
  - controlSequenceOfOperation (cooling only, cooling with reheat, heating only, heating with reheat, cooling and heating, cooling and heating with reheat)
- If supports "Heat"
  - occupiedHeatingSetpoint (numeric)
  - minHeatSetpointLimit (numeric)
  - maxHeatSetpointLimit (numeric)
- If supports "Cool"
  - occupiedCoolingSetpoint (numeric)
  - minCoolSetpointLimit (numeric)
  - maxHeatSetpointLimit (numeric)
- If supports "Auto"
  - thermostatRunningMode (off, cool, heat)
  - minSetpointDeadBand (numeric)

Initially i thought i need to set min/max setpoint limits equally to min_temp and max_temp from HA.
Now i found the following explanation for `minSetpointDeadBand`:

> On devices which support the AUTO feature, this attribute shall indicate the minimum difference between the Heat Setpoint and the Cool Setpoint.
> 
> Refer to Setpoint Limits for constraints. If an attempt is made to set this attribute to a value which conflicts with setpoint values then those setpoints shall be adjusted by the minimum amount to permit this attribute to be set to the desired value. If an attempt is made to set this attribute to a value which is not consistent with the constraints and cannot be resolved by modifying setpoints then a response with the status code CONSTRAINT_ERROR shall be returned.

Can someone please explain in detail HOW the HA attributes shall be mapped to the named matter properties?

**Comment by t0bst4r** [comment]
Just released a fix which sets "minSetpointDeadBand" to `0`, but still i don't know what's the right solution.

**Comment by pkoutsovasilis** [comment]
> Just released a fix which sets "minSetpointDeadBand" to `0`, but still i don't know what's the right solution.

Now the service manages to boot but I can't control my climate devices through google home, so observations:
- auto mode is not visible but through Home Assistant I can set it
- Turning it on the first time does nothing
- Trying to turn it on for a second time results in matterhub showing a wrong state (e.g. climate is on at Cool) but this is not what Home Assistant reports

Some info logs:
```
matterhub-1  | [ 2024-11-09T12:39:38.939Z ] [ INFO  ] [ matter.js / Behavior                               ]: Write 7515dde831d545e28af9bb707b38216e.aggregator.climate_office_aircondition.thermostat.state.systemMode via online#9f1d1bc@220268e7
matterhub-1  | [ 2024-11-09T12:39:38.942Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of 7515dde831d545e28af9bb707b38216e.aggregator.climate_office_aircondition.thermostat.state: Referencing 7515dde831d545e28af9bb707b38216e.aggregator.climate_office_aircondition.homeAssistant.state: This value is no longer available because its context has exited (1)
matterhub-1  |   at get value [as value] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:122:15)
matterhub-1  |   at descriptor.get [as entity] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:150:49)
matterhub-1  |   at ThermostatServer.systemModeChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2361:44)
matterhub-1  |   at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
matterhub-1  |   at ObservableProxy.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
matterhub-1  |   at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
matterhub-1  |   at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:109:12)
matterhub-1  |   at emitChanged (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:332:30)
matterhub-1  |   at Object.postCommit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:338:12)
matterhub-1  |   at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/transaction/Tx.js:465:39
```

**Comment by KipK** [comment]
Just tested too.
All the thermostats are now displayed as deactvited while they're currently in heat mode.

![Screenshot_20241109-154200](https://github.com/user-attachments/assets/3ae2a76b-b24a-46be-b510-cf0ad0fe5486)

Can't set no temperature or mode changes. 
Min Max setpoint range were ok before, now the value goes from -273 to 327.5 °C ^^

on your attribute list posted above, it miss the running state: hvac_action (heating, cooling, off).
That's the property that needs to be matched to its matter equivalen ( thought it was thermostatRunningMode according to matter specs, not only for auto, but perhaps I4ve missed another property ) or the UI always display the thermostat as not heating/cooling

**Comment by KipK** [comment]
I've found the correct matter atttribute for state, it's ThermostatRunningState not ThermostatRunningMode :

4.3.9.34. ThermostatRunningState Attribute
This attribute SHALL indicate the current relay state of the heat, cool, and fan relays.
Unimplemented outputs SHALL be treated as if they were Off

**Comment by t0bst4r** [comment]
okay, thank you very much!

To sum it up, i'll do:

- `matter.localTemperature` = `ha.current_temperature`
- `matter.minHeatSetpointLimit` = `matter.minCoolSetpointLimit` = `ha.min_temp`
- `matter.maxHeatSetpointLimit` = `matter.maxCoolSetpointLimit` = `ha.max_temp`
- `matter.systemMode` = `ha.hvac_action`
  - `ha.off` -> `matter.Off`
  - `ha.preheating` -> `matter.Heat`
  - `ha.heating` -> `matter.Heat`
  - `ha.cooling` -> `matter.Cool`
  - `ha.drying` -> `matter.Dry`
  - `ha.fan` -> `matter.FanOnly`
  - `ha.idle` -> `matter.Sleep`
  - `ha.defrosting` -> `matter.Heat`
  - `nothing` -> `matter.Auto` (hvac_mode would have an "auto" value) 
  - `nothing` -> `matter.EmergencyHeat`
  - `nothing` -> `matter.Precooling`
- `matter.thermostatRunningMode` = only allowed for `systemMode = auto`, but this never happens?
- `matter.thermostatRunningState` = `ha.hvac_action`
  - `ha.off` -> `{ heat: false, cool: false, fan: false }`
  - `ha.preheating` -> `{ heat: true, cool: false, fan: false }`
  - `ha.heating` -> `{ heat: true, cool: false, fan: false }`
  - `ha.cooling` -> `{ heat: false, cool: true, fan: false }`
  - `ha.drying` -> `{ heat: true, cool: false, fan: true }` (if possible)
  - `ha.fan` -> `{ heat: false, cool: false, fan: true }`
  - `ha.idle` -> `{ heat: false, cool: false, fan: false }`
  - `ha.defrosting` -> `{ heat: true, cool: false, fan: false }`

Those properties are REQUIRED in matter, so what could be right value?
- `matter.occupiedHeatingSetpoint` = `matter.occupiedCoolingSetpoint` = `ha.temperature` (target temperature)
- `matter.minSetpointDeadBand` = `0`

In this scenario, we will never use `hvac_mode`, but always `hvac_action`.

@KipK can you please validate ❤️

**Comment by KipK** [comment]
That sounds all ok 👍 
For those ones I'm also agree with those ( can be changed later depending of user feedback anyway )
```

ha.drying -> matter.Heat 
ha.fan -> matter.Off 
ha.idle -> matter.Off 
ha.defrosting -> matter.Heat 
```


#Those properties are REQUIRED in matter, so what could be right value?

matter.occupiedHeatingSetpoint = matter.occupiedCoolingSetpoint = ha.temperature (target temperature)
matter.minSetpointDeadBand = 0

Are you sure of that ? Here is what I4ve found on the doc:, seems it's only for scene management

_4.3.9.1. Scene Table Extensions
If the Scenes Management server cluster is implemented on the same endpoint, the following
attributes SHALL be part of the ExtensionFieldSetStruct of the Scene Table. If the implicit form of
the ExtensionFieldSetStruct is used, the order of the attributes in the AttributeValueList is in the
given order, i.e., the attribute listed as 1 is added first:
1. OccupiedCoolingSetpoint
2. OccupiedHeatingSetpoint
3. SystemMode_

**Comment by t0bst4r** [comment]
okay thank you.
i already released it, can you please test 🙂 

i'll have a look at those three properties later. is it problem to set them like i did?

**Comment by KipK** [comment]
no it should be ok as it won't be used anyway.. I'm testing now. Thanks

**Comment by KipK** [comment]
Just a first shot, it crashes if one of my thermostat is unavailable ( this one is a portable heater, and si not always available:
`
 Caused by: Validating 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_duux_threesixty_2.thermostat.state: Conformance "M": Matter requires you to set this attribute (128)`

I'm removing it for now to test

**Comment by KipK** [comment]
So I don't get what's wrong but:

Thermostat is displayed as disabled but it's on heat mode. 
setpoint is not in sync with the real one. But changing it from GH, set the temp on the thermostat.
min max values are still wrong. It's strange as you did it this way pre alpha 19 and it was ok.

**Comment by KipK** [comment]
Just to be sure, ha.hvac_mode , is the climate entity value ? I have doubt as it's displayed as disabled. There's no hvac_mode attribute, it's the main entity on HA.

I've also found something I didn't knew. some Climate entity can miss the hvac_action attribute ( that's the crash I got on previous post ) 
In this case, we should also use the climate entity value to match with matter.thermostatRunningMode off/ heating, cooling

**Comment by t0bst4r** [comment]
> Just a first shot, it crashes if one of my thermostat is unavailable ( this one is a portable heater, and si not always available

It seems that `localTemperature` is required, but what to take if it is not available / null? I've seen a feature i could activate, called "LocalTemperatureNotExposed" - I'll check that, but that's for later 😁 

> Thermostat is displayed as disabled but it's on heat mode.

> Just to be sure, ha.hvac_mode , is the climate entity value ? I have doubt as it's displayed as disabled. There's no hvac_mode attribute, it's the main entity on HA.

I just noticed that, too. But, Home Assistant documentation says that `hvac_mode` is required.
https://developers.home-assistant.io/docs/core/entity/climate/
It's used to determine the state, but is it the same?

**Comment by t0bst4r** [comment]
I‘d go with a mix of all properties, just to be sure.

for system mode:
1. hvac_mode
2. state value
3. Off

for thermostat running mode:
1. hvac_action
2. state value
3. Off

for thermostat running state:
1. hvac_action
2. State value
3. All off

unfortunately I cannot find the possible values of state value. Is it the same as hvac_mode + `unavailable` ?

Btw. the state value "unavailable" can be used for every domain to determine its availability and to set it in basic information cluster. Then google home knows about this, too.

**Comment by KipK** [comment]
state values are the same as hvac_modes

**Comment by t0bst4r** [comment]
Just found this in home assistant core code of the climate entity:

```python
    def state(self) -> str | None:
        """Return the current state."""
        hvac_mode = self.hvac_mode
        if hvac_mode is None:
            return None
        # Support hvac_mode as string for custom integration backwards compatibility
        if not isinstance(hvac_mode, HVACMode):
            return HVACMode(hvac_mode).value  # type: ignore[unreachable]
        return hvac_mode.value
```

so seems to be the same

**Comment by KipK** [comment]
> It seems that `localTemperature` is required, but what to take if it is not available / null? I've seen a feature i could activate, called "LocalTemperatureNotExposed" - I'll check that, but that's for later 😁

I think it comes from the fact all attributes were not published yet ( those are MQTT thermostats ) when Matter bridge started as HA has just restarted.

**Comment by KipK** [comment]
Can't start anymore the addon, I get this error like it doesn't find the state, not sure what I have changed since, but all attributes looks ok:

![image](https://github.com/user-attachments/assets/59f99894-6fb7-4b83-8fca-889b819422d4)

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.thermostat.state: Conformance "M": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at Thermostat$State.set [as localTemperature] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at Function.assign (<anonymous>)
        at ThermostatServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2262:16)
```

**Comment by t0bst4r** [comment]
Maybe i mixed around a bit with null and undefined for local temperature 😀 
Required attribute, but null is allowed - this is not the same as optional attribute, where undefined is allowed.

i just released another change using the entity's state value as fallback. At least this works for me with my virtual climate.

**Comment by t0bst4r** [comment]
I've also added a "show details" checkbox in the UI when hovering values. Maybe this helps debugging.

![grafik](https://github.com/user-attachments/assets/b9757189-d638-4480-9627-4ab4192016b3)

**Comment by KipK** [comment]
new error nows, with same thermostat attributes posted before ;)

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.thermostat.state: Conformance "HEAT": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at Thermostat$State.set [as occupiedHeatingSetpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
        at Function.assign (<anonymous>)
        at ThermostatServer.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2262:16)
```

**Comment by KipK** [comment]
I have another thermostat that works with. Haven't find any missing stuff in the entities.
First one on screenshot below is not crashing at startup. Second one and allo the same as this one ends with the previous post crash.

![image](https://github.com/user-attachments/assets/5482eb74-4b94-46ab-88e8-bfa8c7e0d932)


For the working one, it nows display the selected mode and can switch between off/heat
temperature selection works too.

min max setpoints don't. 

and running state too:
![image](https://github.com/user-attachments/assets/4643cf7a-08ed-46b7-bb41-05062009a690)

heating:
```
online#5e8199b@88f90ed3
{
  "localTemperature": 1600,
  "systemMode": 4,
  "thermostatRunningState": {
    "heat": true
  },
  "occupiedHeatingSetpoint": 2000,
  "minHeatSetpointLimit": 1500,
  "maxHeatSetpointLimit": 2500,
  "controlSequenceOfOperation": 2
}
```
off
{
  "localTemperature": 1600,
  "systemMode": 0,
  "thermostatRunningState": {},
  "occupiedHeatingSetpoint": 2000,
  "minHeatSetpointLimit": 1500,
  "maxHeatSetpointLimit": 2500,
  "controlSequenceOfOperation": 2
}

**Comment by t0bst4r** [comment]
Okay let’s start with the errors…

### the failing climate
Maybe there is a problem with those float values in the second climate?
At least I am setting `occupiedHeatingSetpoint` to the `temperature` property, so it should not be undefined. 
I‘ll check if the conversion works or if it somehow results in `NaN` (invalid value).

### unable to set heating setpoint
Looking at your working climate entity it has min_temp of 15. the error message you posted says that it’s trying to set a temperature of 14.5
So yes I’d expect that to be forbidden. Why is that even possible in google home?

### running state
At least the properties look as expected, right?
So we need to figure out what’s missing for google home?

**Comment by KipK** [comment]
>unable to set heating setpoint
setpoint works, I've confirmed it above.

> Looking at your working climate entity it has min_temp of 15. the error message you posted says that it’s trying to set a temperature of 14.5
> So yes I’d expect that to be forbidden. Why is that even possible in google home?

The log I've posted is for the min/max range properties not working on GH ( I'm pretty sure they were ok pre alpha 19 ). 
The UI on google nows  shows a range of -273 to 327.5  The log is after receiving an out of range setpoit from GH.
Too bad we can't have logs from google home.

>At least the properties look as expected, right?
Yes the props posted are ok. 
I was wondering if the thermostatRunningState bitmask is correct, or if they don't use thermostatRunningMode as state even not in auto. 
You have Alexa on your side ? I wonder how it goes

**Comment by t0bst4r** [comment]
Yes, Alexa seems to work as expected.

overview in Alexa app:
![IMG_4824](https://github.com/user-attachments/assets/ef8fd462-e02f-4efc-954b-9eed12d6f770)
It’s showing "heating" and "off" states correctly.

details:
![IMG_4825](https://github.com/user-attachments/assets/179f84b1-9c9f-4083-b5b9-1c274272e0ee)
When trying to increase above the max it tells me that this is not possible.

Settings:
![IMG_4823](https://github.com/user-attachments/assets/fbacdf04-8162-456e-9f74-bfa9d5b283ed)

there are two things that look weird to me:
1. why is it possible to change the max heat from within Alexa? Anyway it fails when changing.
2. in the background of the settings screen you can see "Fahrenheit" as unit. That’s not true - matter uses Celsius, my default unit in Alexa and HA are Celsius. And when changing it to Celsius in those device settings, it has no effect and stays "Fahrenheit". Anyway it’s not shown anywhere.

**Comment by KipK** [comment]
>why is it possible to change the max heat from within Alexa? Anyway it fails when changing.

Perhaps those attributes are needed too:

AbsMinHeatSetpoinbtLimit
AbsMaxHeatSEtpointLimit
AbsMinCoolSetpointLimit
AbsMaxCoolSetpointLimit
Those are the hardware manufacturer limits, they should prevent the range settings you have to go above those limits. 
And then Alexa keeps MinHeatSetpoinbtLimit, etc for itself.

_This attribute SHALL indicate the absolute minimum level that the heating setpoint MAY be set to.
This is a limitation imposed by the manufacturer.
Refer to Setpoint Limits for constraints_

Do you think the Thermostat User Interface Configuration Cluster is needed somehow ? 
It has TemperatureDisplayModeEnum prop.

**Comment by radurambet** [comment]
I have to tell you that Climate is a total mess as Zigbee devices usually do not work well with Google Home from HA.
Main reason is that each device has its own working mode. Some work well in Auto , for others heat is auto or reverse , others even they are just TRV's are reported as heating/cooling devices. Others are exposing in MQTT  besides auto and programming schedules also "profiles" for instance Heat may mean Full ON , since  Auto may represent the same with Hysteresis , and for othes it may represent weekly schedule. Its a mess.

Thanks to your addon an many other manual fine tunings I managed to make them work , but since there is not an uniform way of addressing this I believe that the only suitable way would be the posibility for the user to "adjust" parameters and make Matter.heat = Zigbee.Auto or whatever it is.

So if you could expose in thermostat config this options then the skilled HA user would make it work by himself.

Other than that there is another Quirck : In Google Home, Auto does not let you adjust temp (since is "auto") but for some TRV's it may be exactly the needed setting. As I said , a mess.

I have Beca BRT100 TRV, Avatto TRV10 , Avatto TRV7, Moes TS601 , if needed I can help with testing/debugging.

**Comment by KipK** [comment]
hi

Tested alpha 27, and now the thermostat that was still not crashing at startup make it crash too : 

```
[ 2024-11-12T11:14:53.912Z ] [ INFO  ] [ matter.js / Node                                   ]: 8f7ba291df5149adb82cb5badf1bf9f6 going online
[ 2024-11-12T11:14:53.957Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back initialize<8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_duux_threesixty_2>#1bd due to error: Behaviors have errors
home-assistant-matter-hub start
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_duux_threesixty_2.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_duux_threesixty_2.thermostat.state: Conformance "HEAT": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at Thermostat$State.set [as occupiedHeatingSetpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
```

**Comment by t0bst4r** [comment]
> Perhaps those attributes are needed too:
> 
> AbsMinHeatSetpoinbtLimit
> AbsMaxHeatSEtpointLimit
> AbsMinCoolSetpointLimit
> AbsMaxCoolSetpointLimit

I've now added these, too.

```
Behaviors have errors
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/endpoint/properties/Behaviors.js:128:21
      at all (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:375:17)
      at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Construction.js:365:11
      Cause #0: Error initializing 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_duux_threesixty_2.thermostat
        at crash (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/BehaviorBacking.js:48:13)
      Caused by: Validating 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_duux_threesixty_2.thermostat.state: Conformance "HEAT": Matter requires you to set this attribute (128)
        at requireValue (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance-compiler.js:300:13)
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/validation/conformance.js:13:15
        at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:135:13
        at Object.change (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/Datasource.js:155:7)
        at Thermostat$State.set [as occupiedHeatingSetpoint] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/state/managed/values/StructManager.js:105:32)
```

For now i have added a fallback to occupied heating setpoint (20°C). Doesn't really make sense, but let's try it out. Could be a matter of milliseconds.

**Comment by t0bst4r** [comment]
> I have to tell you that Climate is a total mess in Home Assistant in general as Zigbee devices usually do not work well with Google Home from HA. Main reason is that each device has its own working mode. Some work well in Auto , for others heat is auto or reverse , others even they are just TRV's are reported as heating/cooling devices. Others are exposing in MQTT besides auto and programming schedules also "profiles" for instance Heat may mean Full ON , since Auto may represent the same with Hysteresis , and for othes it may represent weekly schedule. Its a mess.
> 
> Thanks to your addon and many other manual fine tunings I managed to make them work , but since there is not an uniform way of addressing this I believe that the only suitable way would be the posibility for the user to "adjust" parameters and make Matter.heat = Zigbee.Auto or whatever it is.
> 
> So if you could expose in thermostat config this options then the skilled HA user would make it work by himself.
> 
> Other than that there is another Quirk : In Google Home, Auto does not let you adjust temp (since is "auto") but for some TRVs it may be exactly the needed setting. As I said , a mess.
> 
> I have Beca BRT100 TRV, Avatto TRV10 , Avatto TRV7, Moes TS601 , if needed I can help with testing/debugging.

That's a whole new feature. Let's get them working in general before making advanced configurations. Advanced users could also create a template climate to work around those problems.

**Comment by KipK** [comment]
alpha 20 solve the starting crash. Now all therms appears again.

New error in log appear with humidity cluster :

```
[ 2024-11-12T14:03:34.794Z ] [ ERROR ] [ matter.js / Transaction                            ]: Error post-commit of 8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.homeAssistant.state: Error in reactor<8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.relativeHumidityMeasurement.update>: reactor<8f7ba291df5149adb82cb5badf1bf9f6.aggregator.climate_jeedom_thermostat_salon_thermostat_salon.relativeHumidityMeasurement.update> returned a Promise but the observable is synchronous; you must set the "offline" option so this reactor runs with a dedicated transaction
  at #react (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:194:15)
  at reactorListener (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/node/dist/esm/behavior/internal/Reactors.js:98:35)
  at emitNext (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@matter/general/dist/esm/util/Observable.js:70:20)
  at BasicObservable.emit (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/@m
```

Tell me when you want deeper debug, I'm not sure you have changedmuch on climate for now. 
Have you seen my previous comment above about ThermostatRunningState not looking to be a bitmask. 
That would explain some mysteries ;)

**Comment by KipK** [comment]
Maybe then there's a bug with ThermostatRunningState on matter.js as it looks ok on your side.

**Comment by t0bst4r** [comment]
Is the app (in general) back working with thermostats?
For the running state / mode topic, i'd suggest re-opening the previous issue or creating a new one, but its not related to "broke thermostats" 😀

**Comment by KipK** [comment]
Agree 👍
It's better with latest.
Setpoint is now well synchronized with hass on booth side + selected mode. 

Still remaining, last reporting one this thread:

-  min/max setpoint still not working. ( Actual range displayed still -273,, 327.5 )
I'm wondering why such extreme values.
- still no running state

**Comment by t0bst4r** [comment]
> min/max setpoint still not working. ( Actual range displayed still -273,, 327.5 )
I'm wondering why such extreme values.

`-273 C` = `0 K` = absolute minimum

but of course it should be set instead of defaulting to the limits. Can you please create another issue for that including the attributes of the climate again to have all details for that in one place. 

> still no running state

I had a chat with one of the developers of matter.js and it doesn’t seem to be a bug on matter side, but on Google and Alexa side. 
It seems that we are doing the mapping of system mode, running mode and running state correctly, but they just don’t use it.
One more question to that: does google home indicate the running mode correctly, when system mode is auto?

**Comment by KipK** [comment]
I don't have thermostat with Auto, but I will try to test with virtual one. Somethings tell me too they're wrongly using ThermostatRunningMode instead.

**Comment by radurambet** [comment]
For sure there is a bug on Google side . On Google Home Displays is shows fine on Google home app there is abolute zero bug. 

Why on one device is ok and on phone app is wrong I don't know . Must be a bug .

**Comment by radurambet** [comment]
I talking about the fact that in Google Home app on mobile the range is between -274 degrees and on Google Home Display is correct . 

Same ecosystem same device one shows ring range other correct . So that mustt be a Google  bug .
